---
title: "paired ttest min-max sire-dam"
output: html_document
date: "2024-10-15"
---

```{r setup, include=FALSE}
library(tidyverse)
```

## filtering pedigree

```{r}
pedigree

two_parents = pedigree %>% 
  filter(!is.na(dam)) %>% 
  gather(key = parent_type, value=parent_id, sire, dam)


two_parents_meters = inner_join(distances_m, two_parents,
                                by = c("offspring_id" = "id", "parent_id" = "parent_id"))
  
  
?inner_join

two_parents_meters
```
## okay now to get min and max
```{r}
max_min_distance = two_parents_meters %>%
  group_by(offspring_id) %>% 
  summarize(max = max(distance),
            min = min(distance))

max_min_distance %>% summary()
```


## ttest time
```{r}
t.test(max_min_distance$max, max_min_distance$min, paired=T)

two_parents_meters %>% 
  gather(key=group, value=distance, max, min)

max_min_distance %>%
  gather(key=group, value=distance, max, min) %>%
  summary()

max_min_distance %>%
  gather(key=group, value=distance, max, min) %>%
  ggplot(mapping=aes(x=distance, fill=group)) +
  geom_histogram()
```

```{r}
two_parents_meters %>%
  gather(key=group, value=distance, max, min) %>% 
  summary()
```



